src/objects/Band__c.object
<CustomObject>
    <fields>
        <fullName>Home_City__c</fullName>
        <label>Home City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_State__c</fullName>
        <label>Home State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Url__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour</label>
        <referenceTo>Tour__c</referenceTo>
        <relationshipLabel>Bands</relationshipLabel>
        <relationshipName>Bands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transportation__c</fullName>
        <label>Transportation</label>
        <picklist>
            <picklistValues>
                <fullName>Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Band</label>
    <nameField>
        <label>Band Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tour__c.object
<CustomObject>
    <description>Tours for tour management system example.</description>
    <label>Tour</label>
    <nameField>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TourOverview.cls
public with sharing class TourOverview {

	Public List<Band__c> bands {get;set;}
	Public string approve {get;set;}
		


	public TourOverview() {

		bands = [SELECT Id, approved__c, name, home_city__c, home_state__c, image_url__c, members__c, tour__c, transportation__c FROM band__c WHERE tour__c = :ApexPages.currentPage().getParameters().get('id')];	
	}

	public pageReference approveBand() {
		band__c b = [SELECT Id, approved__c from Band__c WHERE Id= :approve];
		b.approved__c = true;
		update b;
		return null;
	}
}