src/objects/Tour_Date__c.object
<CustomObject>
    <description>Tour Dates for the tour management example</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tour Date</label>
    <nameField>
        <displayFormat>Stop {0000}</displayFormat>
        <label>Tour Date</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TEST_getLatLong.cls
@isTest
private class TEST_getLatLong {
	
	@isTest static void test_method_one() {
		tour_date__c v = new tour_date__c(street__c ='2822 Kilburn Ct.', city__c = 'rochester hills', state__c='Michigan', zip__c='48306', country__c='United States');
		Test.startTest();
		insert v;		
		Test.stopTest();
		system.assert(v.Location__Latitude__s == null);
		system.assert(v.Location__longitude__s == null);

	}
	
	
}